<?php
/**
 * NOTICE OF LICENSE
 *
 * This source file is subject to the Open Software License (OSL 3.0)
 * that is available through the world-wide-web at this URL:
 * http://opensource.org/licenses/osl-3.0.php
 */

use Magenerds\WysiwygWidget\Block\Widget\Editor;
use Magento\Framework\View\Element\Template;
use Magenerds\PageDesigner\Utils\HtmlRenderer;

/**
 * Template for the Page Designer configuration
 *
 * @package     Magenerds\PageDesigner
 * @file        config.phtml
 * @copyright   Copyright (c) 2019 TechDivision GmbH (https://www.techdivision.com)
 * @site        https://www.techdivision.com/
 * @author      Simon Sippert <s.sippert@techdivision.com>
 */

/** @var Template $block */
?>
<script>
    /**
     * Page Designer Configuration Object
     *
     * @type {{}}
     */
    window.pageDesignerConfig = {
        // widget types with wysiwyg content
        wysiwygWidgetTypes: <?= json_encode([Editor::class]); ?>,
        // settings route url (columns)
        columnSettingsUrl: <?= json_encode($block->getUrl('adminhtml/pageDesigner/columnSettings')); ?>,
        // settings route url (rows)
        rowSettingsUrl: <?= json_encode($block->getUrl('adminhtml/pageDesigner/rowSettings')); ?>,
        // settings save callback
        settingsCallback: null,
        /**
         * Set settings function. Gets called by overlay save button.
         */
        setSettings: function () {
            // retrieve data
            var data = jQuery(this).closest('form').serializeArray();

            // define json
            var json = {};
            var content = '';

            // add data to json
            jQuery(data).each(function () {
                var name = this.name === '<?= HtmlRenderer::JSON_PROPERTY_CSS_CLASS ?>[]' ?
                    '<?= HtmlRenderer::JSON_PROPERTY_CSS_CLASS ?>' : this.name;
                content = (content.length > 0) ? content + ' ' + this.value : this.value;
                json[name] = content;
            });

            // save settings on column
            window.pageDesignerConfig.settingsCallback(json);

            // close modal
            jQuery('.modals-wrapper .modal-slide._show .action-close').last().trigger('click');
        }
    };
</script>
